[package]
name = "rpc-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
interprocess = "2"
libc = "0.2"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
